#! /bin/bash
img=${1:-webui}

set -x
docker run --cpus 4 -it \
         --name ${USER}_${img} \
         -v /home/${USER}:/home/${USER} \
         -u $(id -u):$(id -g) \
         -w $(pwd) \
         -v '/etc/group:/etc/group:ro' \
         -v '/etc/passwd:/etc/passwd:ro' \
         -v '/etc/shadow:/etc/shadow:ro' --rm ${img} bash